Disable Wheather2_to_Bacnet and MultipleDevices
These projects don't build because of errors in the code

yabe/AllYabeProjects.sln (default targets) -> (Build target) ->
yabe/CodeExamples/Wheather2_to_Bacnet/Wheather2_to_Bacnet.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	BacnetActivity.cs(64,70): error CS0426: The type name 'WriteNotificationCallbackHandler' does not exist in the type 'BaCSharpObject'

yabe/AllYabeProjects.sln (default targets) -> (Build target) ->
yabe/CodeExamples/MultipleDevices/MultipleDevices.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	BacnetActivity.cs(65,70): error CS0426: The type name 'WriteNotificationCallbackHandler' does not exist in the type 'BaCSharpObject'
```